### ISSUE TITLE
[BUG] OSError with egl

### ISSUE THREAD

**Issue by rayzchen** [pyunity/pyunity#47]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### System info

```plain text
Loaded config
Detected settings.json entry
Using window provider GLFW
Loaded PyUnity version 0.9.0
##############################
         VERSION INFO
##############################
PyUnity version: v0.9.0
Python version: v3.9.4-final
Operating system: Windows 10
Machine: AMD64
Python architecture: 32bit
Dependencies:
Warning: PyUnity not ran as an installed package
- pyopengl version: 3.1.5
- pillow version: 9.0.1
- pysdl2 version: 0.9.11
- pysdl2-dll version: 2.0.20
- pyglm version: 2.5.7
- importlib-resources version: None
```

### Describe the bug

EGL window provider throws OSError when running multiple examples in sequence

### To reproduce

Use `PYUNITY_WINDOW_PROVIDER=egl` and run `python -m pyunity`.

### Traceback

```plain text
Loaded config
Trying EGL as a window provider
Using window provider EGL
Loaded PyUnity version 0.9.0
Warning: Currently broken examples: 3

Example 1
/Cube
/Floor
/Light
/Main Camera
Launching window manager
[<EGLDisplay object at 0x020F8BF8>, <pyunity.window.providers.egl.egl.EGLint_Array_13 object at 0x04F661D8>, <pyunity.window.providers.egl.egl.EGLConfig_Array_1 object at 0x04F66190>, 1, <EGLint object at 0x04F66148>]
Compiling objects
Starting scene
Physics is on
Scene 'Scene' has started
Exiting

Example 2
Launching window manager
[<EGLDisplay object at 0x020F8BF8>, <pyunity.window.providers.egl.egl.EGLint_Array_13 object at 0x0D2FFB20>, <pyunity.window.providers.egl.egl.EGLConfig_Array_1 object at 0x0D2FFD18>, 1, <EGLint object at 0x0D2FFF58>]
Compiling objects
Warning: Detected settings.json entry
Warning: windowCache entry has been set, indicating window checking happened on this import
Warning: settings.json entry may be faulty, removing
Traceback (most recent call last):
  File "C:\Users\raych\AppData\Local\Programs\Python\Python39-32\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\raych\AppData\Local\Programs\Python\Python39-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Ray-Data\python\pyunity\pyunity\__main__.py", line 60, in <module>
    examples.show()
  File "C:\Ray-Data\python\pyunity\pyunity\examples\__init__.py", line 36, in show
    load_example(i)
  File "C:\Ray-Data\python\pyunity\pyunity\examples\__init__.py", line 20, in load_example
    module.main()
  File "C:\Ray-Data\python\pyunity\pyunity\examples\example2\__init__.py", line 55, in main
    SceneManager.LoadScene(scene)
  File "C:\Ray-Data\python\pyunity\pyunity\scenes\sceneManager.py", line 244, in LoadScene
    __loadScene(copy.deepcopy(scene))
  File "C:\Ray-Data\python\pyunity\pyunity\scenes\sceneManager.py", line 282, in __loadScene
    render.compileSkyboxes()
  File "C:\Ray-Data\python\pyunity\pyunity\render.py", line 338, in compileSkyboxes
    skybox.compile()
  File "C:\Ray-Data\python\pyunity\pyunity\files.py", line 313, in compile
    gl.glTexImage2D(gl.GL_TEXTURE_CUBE_MAP_POSITIVE_X + i, 0, gl.GL_RGBA,
  File "src/latebind.pyx", line 39, in OpenGL_accelerate.latebind.LateBind.__call__
  File "src/wrapper.pyx", line 311, in OpenGL_accelerate.wrapper.Wrapper.__call__
OSError: exception: access violation reading 0x00000004
```

### Additional context

Could be caused by using a terminated display but in `pyunity/window/providers/window.py` eglInitialize is called every time the window provider is instantiated. Similar issues also happen when using 32-bit python on 64-bit machine.

**Comment by rayzchen** [comment]
Python 3.10-x64 embeddable package causes a different issue which indicates that the EGL context isn't set up correctly.

**Comment by rayzchen** [comment]
The new `glctx` window provider will use `glcontext` and `wgl` on Windows to create an offscreen context.

**Comment by rayzchen** [comment]
`glctx` is working better than `egl` is, testing on Linux and MacOS is planned.
