### ISSUE TITLE
[BUG] Windows and MacOS actions freeze on `multiprocessing`

### ISSUE THREAD

**Issue by rayzchen** [pyunity/pyunity#49]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### System info

```plain text
Loaded config
Warning: Testing PyUnity, audio is disabled
Loaded PyUnity version 0.9.0
##############################
         VERSION INFO
##############################
PyUnity version: v0.9.0
Python version: v3.8.10-final
Operating system: Windows 10
Machine: AMD64
Python architecture: 64bit
Warning: PyUnity not ran as an installed package
Dependencies:
- pyopengl version: 3.1.6
- pillow version: 9.1.0
- pysdl2 version: 0.9.11
- pysdl2-dll version: 2.0.20
- pyglm version: 2.5.7
- importlib-resources version: 5.7.1
```

### Describe the bug

Windows and MacOS GitHub actions freeze when running `prepare.py`.

### To reproduce

Run `workflows/windows.yml` or `workflows/macos.yml` action

### Traceback

```plain text
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\a\pyunity\pyunity\setup.py", line 22, in <module>
    prepare.cythonize()
  File "D:\a\pyunity\pyunity\prepare.py", line 231, in cythonize
    pool = multiprocessing.Pool(nthreads, initWorker)
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\multiprocessing\context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\multiprocessing\pool.py", line 212, in __init__
    self._repopulate_pool()
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\multiprocessing\pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\multiprocessing\pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.
        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:
            if __name__ == '__main__':
                freeze_support()
                ...
        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

### Additional context

Multiprocessing seems to not be working.

**Comment by rayzchen** [comment]
Cannot directly import `prepare.py` into `setup.py`, must use subprocess. Fixed in 4ab7e7393e3e91941b56ec52646f1b3b15575582.
