### ISSUE TITLE
[BUG] ctypes.ArgumentError: argument 2: <class 'KeyboardInterrupt'>

### ISSUE THREAD

**Issue by rayzchen** [pyunity/pyunity#58]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### System info

```plain text
Loaded config
Detected settings.json entry
Using window provider GLFW
Loaded PyUnity version 0.9.0
##############################
         VERSION INFO
##############################
PyUnity version: v0.9.0
Python version: v3.9.4-final
Operating system: Windows 10
Machine: AMD64
Python architecture: 32bit
Dependencies:
- pyopengl version: 3.1.5
- pillow version: 9.0.1
- pysdl2 version: 0.9.11
- pysdl2-dll version: 2.0.20
- pyglm version: 2.5.7
- importlib-resources version: None
- glfw version: 2.5.3
```

### Describe the bug

Program quits with a large error yet KeyboardInterrupt is not raised and so cannot be caught normally by `SceneManager.__loadScene`.

### To reproduce

Run examples
Press Ctrl+C while an example is running
Repeat until KeyboardInterrupt is raised while an OpenGL function is being called

### Traceback

```plain text
Loaded config
Detected settings.json entry
Using window provider GLFW
Loaded PyUnity version 0.9.0

Example 1
/Cube
/Floor
/Light
/Main Camera
Launching window manager
Compiling objects
Starting scene
Physics is on
Scene 'Scene' has started

Example 2
Launching window manager
Compiling objects
Starting scene
Physics is on
Scene 'Scene' has started
Traceback (most recent call last):
  File "C:\Users\raych\AppData\Local\Programs\Python\Python39-32\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\raych\AppData\Local\Programs\Python\Python39-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Ray-Data\python\pyunity\pyunity\__main__.py", line 60, in <module>
    examples.show()
  File "C:\Ray-Data\python\pyunity\pyunity\examples\__init__.py", line 36, in show
    loadExample(i)
  File "C:\Ray-Data\python\pyunity\pyunity\examples\__init__.py", line 20, in loadExample
    module.main()
  File "C:\Ray-Data\python\pyunity\pyunity\examples\example2\__init__.py", line 55, in main
    SceneManager.LoadScene(scene)
  File "C:\Ray-Data\python\pyunity\pyunity\scenes\sceneManager.py", line 243, in LoadScene
    __loadScene(copy.deepcopy(scene))
  File "C:\Ray-Data\python\pyunity\pyunity\scenes\sceneManager.py", line 308, in __loadScene
    windowObject.start(scene.update)
  File "C:\Ray-Data\python\pyunity\pyunity\window\providers\glfw\window.py", line 145, in start
    self.updateFunc()
  File "C:\Ray-Data\python\pyunity\pyunity\scenes\scene.py", line 502, in update
    self.Render()
  File "C:\Ray-Data\python\pyunity\pyunity\scenes\scene.py", line 518, in Render
    self.mainCamera.Render(renderers, lights)
  File "C:\Ray-Data\python\pyunity\pyunity\render.py", line 732, in Render
    self.RenderScene(renderers, lights)
  File "C:\Ray-Data\python\pyunity\pyunity\render.py", line 727, in RenderScene
    self.SetupShader(lights)
  File "C:\Ray-Data\python\pyunity\pyunity\render.py", line 637, in SetupShader
    self.shader.setVec3(b"viewPos", list(
  File "C:\Ray-Data\python\pyunity\pyunity\render.py", line 292, in setVec3
    location = gl.glGetUniformLocation(self.program, var)
  File "C:\Users\raych\AppData\Local\Programs\Python\Python39-32\lib\site-packages\OpenGL\latebind.py", line 63, in __call__
    return self.wrapperFunction( self.baseFunction, *args, **named )
  File "C:\Users\raych\AppData\Local\Programs\Python\Python39-32\lib\site-packages\OpenGL\GL\VERSION\GL_2_0.py", line 430, in glGetUniformLocation
    return baseOperation( program, name )
ctypes.ArgumentError: argument 2: <class 'KeyboardInterrupt'>:
```

### Additional context

To do with raising KeyboardInterrupt while running an OpenGL function

**Comment by rayzchen** [comment]
Linked to #40

**Comment by rayzchen** [comment]
Need to reproduce with new event loop.

**Comment by rayzchen** [comment]
Possible that this was patched on pyopengl's side.
